---
db:
  type: sqlite3

http:
  server:
    host: 127.0.0.1
    port: 8080

cache:
  type: memory

admin:
  key: test_key

cors:
  origins:
    - "*"
  methods:
    - GET
    - POST
    - PUT
    - DELETE
  allowed_headers:
  exposed_headers:
  allow_credentials: true
