---
version: '3'
services:
  wormhole:
    image: "primasio/wormhole"
    ports:
    - "80:80"
    volumes:
    - /primas/components/wormhole/config:/wormhole/config
    - /primas/components/wormhole/logs:/wormhole/logs
